services:
  portfolio:
    image: unmugviolet/portfolio-xp:latest
    ports:
      - "35000:35000"
    build:
      context: .
      args:
        VITE_APP_PORTFOLIO_DOMAIN_NAME: ${VITE_APP_PORTFOLIO_DOMAIN_NAME}
        NODE_ENV: ${NODE_ENV}
        VITE_APP_ADMIN_NAME: ${VITE_APP_ADMIN_NAME}
        VITE_APP_ADMIN_EMAIL_ADDRESS: ${VITE_APP_ADMIN_EMAIL_ADDRESS}
        VITE_APP_PUBLIC_KEY: ${VITE_APP_PUBLIC_KEY}
        VITE_APP_EMAILJS_SERVICE_ID: ${VITE_APP_EMAILJS_SERVICE_ID}
        VITE_APP_EMAILJS_TEMPLATE_ID: ${VITE_APP_EMAILJS_TEMPLATE_ID}
    restart: unless-stopped
